# History about R
Bell labs develops s language in 1976. In 1993 Ross lhaka and Robert Gentleman created R in new zealand. R become free source in 1995. R version 1.0.0 is released in 2000 to the public. IDE Rstdio is release in 2011.

 ## Introduction
R is a programming language and software environment for statical computing and graphics supported by the R foundation. R is not like a general-purpose programming language like Java, C, because it was created by statisticians as an active environment. Interactivity is the critical characteristic that allows R to explore our data. It is also a programming language and development environment for statistical testing and graphical testing. Each statistical testing is either linear, non-linear modeling, classification or many more. Different types of the plot are required while doing data analysis. In order to run R, we will use IDE(according to Wikipedia an integrated development environment(IDE) is a software application that provides comprehensive facilities to the programmer for software development). The core component which is required for every R program is BaseR. These core components contain only the code importing bits that run our code successfully.
  


## Installing and Setting up R in your Windows
### Step 1: Downloading installation file 
* Download R tools from [Official Website](https://cran.r-project.org/bin/windows/Rtools/)
* Next, we need to have an IDE, most popular one is Rstudio. We can download it from [this link](https://www.rstudio.com/products/rstudio/download/).

After downloading installation file, install them on desired places and then open the console.
Now we can write our R codes within console or we can do it via Rstudio. 

I prefer to use Jupyter Notebook for runing R because it is more friendly for me. A good tutorial is available at [Anaconda's Documentation](https://docs.anaconda.com/anaconda/navigator/tutorials/r-lang/).

### Assigning Variable and operator in R
 A Variable is a container that stores values. An assignment statement set or reset the value store in the storage location(s) denoted by variable name(by Wikipedia). The assignment operator is a command that is it telling the computer to assign the text apple to the variable product. we can also assign by `assign('products', ' apple)`. We can assign the variable in R in many ways like below.

#### Way 1

In [2]:

('apple'-> product)


[1] "apple"

#### Way 2

In [3]:
(product = 'apple')

[1] "apple"

#### Way 3

In [8]:
assign( product,  'apple')

In [2]:
(product = 'apple')

[1] "apple"

## Logical Operators in R 
Logical operator means those which gives `True` and `False` value. For example

### Example 1

In [5]:
apple <- 2
banana <- 3
mostexpensive <- banana> apple
mostexpensive

[1] TRUE

### Example 2

In [6]:
apple <- 2
banana <- 3
mostexpensive <- banana< apple
mostexpensive

[1] FALSE

### Example 3

In [3]:
apple <- 2
banana <- 2
mostexpensive <- banana == apple
mostexpensive

[1] TRUE

### Example 4

In [4]:
apple <- 2
banana <- 2
mostexpensive <- banana != apple
mostexpensive

[1] FALSE

In [5]:
result <- (1+2)*3 # it does not give any value because it assume that result will be store for future use.

In [6]:
assign('result2',(3+1-2)*3)
print(result2)

[1] 6


In [7]:
calculation <- result <- 15
calculation
result

[1] 15

[1] 15

In [8]:
(abs(-6))
(factorial(4))

[1] 6

[1] 24

## Some Commonly Used Data Types in R
Data is centre for analysis if there is no data there is no analysis. Every piece of data are working with some characteristics thses characteristics can be summarize with data type.
* `Character` :
Anything inside quotation is a character.
* `Number`: 
Number in R is double. Working with whole and fraction is a unique feature of double. Another is integer. 
* `Integer` 
Integer is actually simplified version of double. It store data as a string we must use capital letter L. In our use we need to use double rather than integer.
* `Logical(Boolean)`:
`Yes` or `No`. Also `T` or `F`.
* `Complex Number`:
$$ 2 + 6i $$
* `Raw`:
It is not so popular data type. It is not easy to create variable of raw type. If we really need to create raw function as a result of calling this function we get raw type data.

All the fundamental data types are called atomic data type.


### Examples

In [9]:
a <- 2L
class(a)


[1] "integer"

In [10]:
a <- 2
class(a)

[1] "numeric"

In [17]:
typeof(a)

[1] "double"

In [11]:
quantity <- 2
typeof(quantity)

[1] "double"

In [2]:
quantity_integer <- 2L
typeof(quantity_integer)

[1] "integer"

# Comments
Comments are used to give important information about the code. Comments are not run by the program but a programmer writes it for better explanation of the code.

In [13]:
# This is a comment line


## Exploring vectors and factors
Data structure as name suggest represent way to organize data to facilate different operations to perform faster calculations.

* `Vectors`:
Collection of data of same structure.
* `Factors`:
Which are used to store categorical data.
* `Array`:
Is a matrix which are generalization of vectors.
* `List\DataFrame`:
Elements of different list are dataframe. List are more complex data structure because they allow us to store other list too. We can think data frame as spreadsheets where  data are organize as columns and rows where each column has specific data type. Within a data frame we have all kinds of datatype but within one column we have only one data type. Other criteria to categorize our data is by dimensional. 

Vector and list are one dimensional objects. Matrices and dataframe are two dimensional data structure. Array are the object that have more than two dimensions.

> Vector have two properties they are one dimensional and containing element of same type.


### Assigning a column vector
Lets assign a column vector,

In [14]:
assign('b',c(1,2,3,4))
print(b)

[1] 1 2 3 4


### Vectors attributes:
* `length`: 
It is denoted by length(a) and its meaning is number of elements.
* `Name`: 
 names(a), it allows us to add element in the list.
* `Type`: 
typeof(a), It gives type of data.

There are six vectors types
* Double
* logical
* character
* complex
* Raw
* Integer


In [9]:
vector <- c("Durga","Puja","Ram","Hari")
vector
length(vector) # length 
names(vector)= "Sita" #names
typeof(vector) # type
vector

[1] "Durga" "Puja"  "Ram"   "Hari"

[1] 4

[1] "character"

Sita    <NA>    <NA>    <NA> 
"Durga"  "Puja"   "Ram"  "Hari"

### Manipulating vectors.
Manipulating of vectors consists of sorting, ordering, indexing.
* `sorting`: Sort the data in some order.
* `Ordering`:
The order function return the index needed to get the vector sort.
* `Indexing`:
Selecting specifics iteam by position.

In [10]:
quantity <- c(1,3,2,5,6,7)
sort(quantity)
order(quantity)

[1] 1 2 3 5 6 7

[1] 1 3 2 4 5 6

In [11]:
a <- c(1,7,36,0,7,5)
a[2]
a[3:5]
a[c(2,4)]
a[c(4,7)]# it return particular element from vector
a[-2]
a[-(2:4)] # it skip the element in the vector.
a[a==1]
a[a>3]
a[a %in%c(2,4)] # it gives matching element.

[1] 7

[1] 36  0  7

[1] 7 0

[1]  0 NA

[1]  1 36  0  7  5

[1] 1 7 5

[1] 1

[1]  7 36  7  5

numeric(0)

### Operating vector
Adding or multiplying vector of different size is called recycling rule. For recycling largest vector must be multiple of small one.

In [12]:
c <- 1:6
d <- 1:3
c * d

[1]  1  4  9  4 10 18

## Sequence generation
It is used to create sequence of elements in a vector. `seq()` function takes length and difference between values as optional argument. In a code below, I take elements in the range 1 to 5 in the interval of 1.5.

Example:

In [16]:
seq(1,5,by = 1.5)

[1] 1.0 2.5 4.0

In [13]:
seq(1,5,by = 3)

[1] 1 4

## Replicating elements
It is used to return the replicating element in the list in a specified times. In the following code I replicate the numbers from 1 to 6 two times. A builtin function `rep()` is used.

Example:

In [17]:
e<- rep(1:6,times = 2)
e

[1] 1 2 3 4 5 6 1 2 3 4 5 6

Example:

In [180]:
x <- rep(c(1),each = 10)
x

[1] 1 1 1 1 1 1 1 1 1 1

## Conversion of different type of data into character type is called implicit coercian
R convert coerced data type into character.

In [15]:
x <- c(1,'two',4,"durga")
x
typeof(x)

[1] "1"     "two"   "4"     "durga"

[1] "character"

## Explicit type coercian
* We do this by typing `as.desire data type`. Explicit type coercian helps us to deal with incorectly catagorized data.
* We can not transfer numeric into character 
* Character into numberic.

In [16]:
num <- 1:5
num_char <- as.character(num)
num_char

[1] "1" "2" "3" "4" "5"

In [17]:
product <- c("apple",1,"banana")
as.numeric(product)

Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"


[1] NA  1 NA

## Installing Packages in R
There are numerous useful packages to do various tasks in R and with those packages, we could do things better and faster way. Once simpler way to install packages is via console;

In [18]:
install.packages("haven")

Installing package into 'C:/Users/Durga Pokharel/Documents/R/win-library/4.1'
(as 'lib' is unspecified)



package 'haven' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Durga Pokharel\AppData\Local\Temp\RtmpIpLzLt\downloaded_packages


In [19]:
library("haven") # allows to read sav file
saq8 <- read_sav("F:/Statisticts with R/CSV file for covid data/SAQ8.sav")

In above example, I first installed package named as `haven` and then I used it to read `sav` file.

# Array

In [50]:
a <- c(1,2,3,4,5,4)
b <- c(4,5,6,7,8,6)
c<- c(3,8,7,5,6,7)
d<- rbind(a,b,c)
d

[,1] [,2] [,3] [,4] [,5] [,6]
a 1    2    3    4    5    4   
b 4    5    6    7    8    6   
c 3    8    7    5    6    7

In [63]:
quantity_day1 <- d 
quantity_day1
quantity_day2 <- d*2
shopping_data <- array(c(quantity_day1,quantity_day2), dim= c(3,6,2))
shopping_data[,,1]


[,1] [,2] [,3] [,4] [,5] [,6]
a 1    2    3    4    5    4   
b 4    5    6    7    8    6   
c 3    8    7    5    6    7

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    2    3    4    5    4   
[2,] 4    5    6    7    8    6   
[3,] 3    8    7    5    6    7

# List

In [64]:
a <- c(1,2,3,4,5,4)
b <- c(4,5,6,7,8,6)
c<- c(3,8,7,5,6,7)
d<- list(a,b,c)
d


[[1]]
[1] 1 2 3 4 5 4

[[2]]
[1] 4 5 6 7 8 6

[[3]]
[1] 3 8 7 5 6 7

In [68]:
basket_detail <- list( store = 'store',product = c('apple','cookies'),price= c(12,45))
basket_detail
basket_detail[[1]]
basket_detail[[2]]
basket_detail[[3]]

$store
[1] "store"

$product
[1] "apple"   "cookies"

$price
[1] 12 45

[1] "store"

[1] "apple"   "cookies"

[1] 12 45